
name: MovieBooking

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Repository
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: maven
    - name: Package Jar
      id: packaging-jar
      shell: bash
      run: mvn clean install
    - name: Generate deployment package
      run: |
        mkdir -p deploy
        cp target/*.jar deploy/application.jar
        cd deploy
        zip -r deploy.zip .
    - name: Display Working Directory
      run: |
        pwd
        ls -la
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: npt02/moviebooking-gitlab
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t npt02/moviebooking-gitlab .
          docker push npt02/moviebooking-gitlab
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Elastic BeanStalk AWS
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: WebMovieBooking
        environment_name: movie-booking-env
        version_label: v1.0.0
        region: ap-southeast-1
        deployment_package: deploy.zip
    - name: Deploy success
      run: echo "Deployed OK!"
